### ISSUE TITLE
Do not upload to rackspace

### ISSUE THREAD

**Issue by mattip** [python-pillow/pillow-wheels#146]
As per matthew-brett/multibuild#304, projects should not upload to rackspace since this is no longer free. Over at [numpy-wheels](https://github.com/MacPython/numpy-wheels/blob/master/.travis.yml#L99), we chose to use anaconda.org for staging. Cython chose to [upload them](https://github.com/MacPython/cython-wheels/blob/master/.travis.yml#L116) to github as [release packages](https://github.com/MacPython/cython-wheels/releases). One advantage to using a shared location is that any of the wheels in that location can be installed with a single `-i https://pypi.anaconda.org/scipy-wheels-nightly/simple` argument to pip.

If you choose the anaconda route, I can give a pillow admin rights to the anaconda staging area.

**Comment by hugovk** [comment]
@wiredfool Please could you check if the Pillow Rackspace account is now being billed?

**Comment by wiredfool** [comment]
No, the account was closed a couple years back.

**Comment by hugovk** [comment]
Okay, that's good.

http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com/ that we use is the same as http://wheels.scipy.org/ mentioned in the [email](https://mail.python.org/pipermail/scipy-dev/2020-February/023990.html) linked in https://github.com/matthew-brett/multibuild/issues/304, that is running up a large bill, so let's shift to something else. 

First off, looks like there's both storage and bandwidth costs. There are 512 `Pillow*` files up there, from 2.3.0 to 7.1.2. I don't think we need anything still hosted there, the important release files are at PyPI. 

Can we tell an admin they can delete all the `Pillow*` files on http://wheels.scipy.org/? 

Second, let's switch to something else. I don't have a strong preference, maybe GitHub Packages would be good, especially if we start building wheels from there.

**Comment by hugovk** [comment]
I've asked an admin to delete the old wheels: 

* https://github.com/matthew-brett/multibuild/issues/304#issuecomment-650502129

**Comment by mattip** [comment]
Would someone like admin perms at https://anaconda.org/scipy-wheels-nightly/numpy/files (for weekly HEAD uploads) and https://anaconda.org/multibuild-wheels-staging/ (for pre-releases) so they can put the upload hashes into the travisCI configuration? Then you could do something like what [numpy-wheels does](https://github.com/MacPython/numpy-wheels/blob/master/.travis.yml#L99) to upload there.

An alternative would be to imitate cython and put the wheels on github https://github.com/MacPython/cython-wheels/releases instead of using the anaconda.org uploads.

**Comment by hugovk** [comment]
@mattip Thanks for the suggestions, I've created #156 to upload to GitHub releases!

**Comment by hugovk** [comment]
#156 merged!

We need to update https://github.com/python-pillow/pillow-wheels#pypi and https://github.com/python-pillow/Pillow/blob/master/RELEASING.md#mac-and-linux:

```sh
wget -m -A 'Pillow-<VERSION>-*' \
http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com
```

It's possible to click via the UI, and there's a bunch of curl/wget commands at, and also https://github.com/gruntwork-io/fetch looks like a handy tool, for example:

```sh
brew install fetch
mkdir /tmp/assets
fetch --repo https://github.com/gruntwork-io/fetch --release-asset="\.exe" --progress --tag ">=v0.3" --progress /tmp/assets
```

**Comment by hugovk** [comment]
All built, except for `3.6 macOS PyPy` due to a temporary network failure:

```
==> Installing openblas
==> Downloading https://homebrew.bintray.com/bottles/openblas-0.2.20_1.high_sierra.bottle.tar.gz
curl: (6) Could not resolve host: homebrew.bintray.com
Error: Failed to download resource "openblas"
Download failed: https://homebrew.bintray.com/bottles/openblas-0.2.20_1.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
curl: (6) Could not resolve host: github.com
Error: Failed to download resource "openblas"
Download failed: https://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
```

https://travis-ci.org/github/python-pillow/pillow-wheels/jobs/717224091

I restarted it.
