### ISSUE TITLE
About link

### ISSUE THREAD

**Issue by radarhere** [python-pillow/pillow-wheels#166]
https://github.com/python-pillow/pillow-wheels shows a link to rackcdn in the About section.

![Screen Shot 2020-10-10 at 12 12 00 pm](https://user-images.githubusercontent.com/3112309/95642060-dad94400-0af1-11eb-9a42-031038fd0c24.png)

This is no longer relevant, as per #146, and should be removed.

**Comment by hugovk** [comment]
Shall we replace it with a link to https://github.com/python-pillow/pillow-wheels/releases?

@aclark4life A task for you!

**Comment by aclark4life** [comment]
@hugovk Done!

**Comment by hugovk** [comment]
Thanks!

**Comment by radarhere** [comment]
Thanks
