### ISSUE TITLE
Reasonable way to run locally?

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/pillow-wheels#171]
@hugovk @nulano 

Because of https://github.com/python-pillow/Pillow/issues/4225, I need to be able to reproduce the production builds locally. Have either of you done anything like this?  It looks like it needs a specially setup trusty virtual machine including modern python & docker, or docker in docker to make it work.

**Comment by hugovk** [comment]
No, I normally develop for Pillow with local, native setup.

Perhaps this is a good base image? https://hub.docker.com/r/matthewbrett/trusty

**Comment by nulano** [comment]
No, I've only done Windows builds locally.

I'm not sure how helpful this is, but when moving this repo to GHA, it looked like the multibuild script runs everything in a fresh Docker image, and only uses the host python for some simple steps before the build. So you could probably use the multibuild script directly, and modify the local copy for testing if needed.

**Comment by hugovk** [comment]
Closing before archiving repo.
