### ISSUE TITLE
Travis CI failing due to missing features: fribidi harfbuzz raqm

### ISSUE THREAD

**Issue by hugovk** [python-pillow/pillow-wheels#198]
Travis CI builds for this repo have had several months of downtime. Since we got new Travis CI credits and re-enabled this repo (https://github.com/python-pillow/Pillow/issues/5028#issuecomment-817903201), the build is failing.

For example:

* https://travis-ci.com/github/python-pillow/pillow-wheels/builds/225368840

Tests run, but then it hangs and times out after features mismatch:

```
...
SKIPPED [1] Tests/test_shell_injection.py:34: cjpeg not available
SKIPPED [1] Tests/test_shell_injection.py:39: Netpbm not available
SKIPPED [1] Tests/test_shell_injection.py:45: Netpbm not available
XFAIL Tests/test_decompression_bomb.py::TestDecompressionBomb::test_exception_ico
  different exception
XFAIL Tests/test_image_resample.py::TestCoreResampleAlphaCorrect::test_levels_rgba
  Current implementation isn't precise enough
XFAIL Tests/test_image_resample.py::TestCoreResampleAlphaCorrect::test_levels_la
  Current implementation isn't precise enough
XPASS Tests/test_file_palm.py::test_p_mode Palm P image is wrong
= 2532 passed, 230 skipped, 3 xfailed, 1 xpassed, 17 warnings in 94.88s (0:01:34) =
Features should be: 'fribidi harfbuzz raqm transp_webp webp_anim webp_mux xcb'; but are 'transp_webp webp_anim webp_mux xcb'
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

The missing features are fribidi harfbuzz raqm.

From `run_tests` in `config.sh`:

https://github.com/python-pillow/pillow-wheels/blob/3b8d91552feac90206c7c638aab3d2bf766a25e6/config.sh#L171-L176

Looks like `run_tests` is called by multibuild.

* Why is there a feature mismatch causing this failure?
* Why is it hanging instead of failing immediately?

**Comment by nulano** [comment]
> The missing features are fribidi harfbuzz raqm.
> ...
> Why is there a feature mismatch causing this failure?

From the 8.2.0 release thread (https://github.com/python-pillow/Pillow/issues/5287#issuecomment-812552683):

> Oops, I don't think anyone actually tested the [Raqm/FriBiDi] PR on Travis. Disabling the check on Travis should be fine as the build is done with the `--enable-raqm` setup flag which ensures Raqm support was built, even if the tests fail to find FriBiDi after installation.

I just haven't got around to submitting a PR implementing this yet. I also don't know if I could test it since the switch (last I checked I was still on .org, and the amount of trial credits on .com is quite limited).

**Comment by hugovk** [comment]
If you're still on org, best to stay there until they actually shut it down, as it uses no credits. I think the capacity problems have settled, at least the few repos I've seen still there.

It's said "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information." literally for months, it was meant to shut down at the end of 2020!

Or if you know what the patch is, we can test it here, or on my com repo, I have credits too.

**Comment by hugovk** [comment]
I think we can close this now, I don't recall any hangs and if it's rare we can restart the build.
