### ISSUE TITLE
Colors are Switched in ImageGrab.grab

### ISSUE THREAD

**Issue by BigDvsRL** [python-pillow/pillow-wheels#263]
ImageGrab.grab switches the Colors up, Red gets Blue and Blue gets Red

Original Text pixel = red 1, green 199, blue 248
Screenshot from that same region is = red 224, green 159, blue 1

so i think Red and blue switched sides

i just noticed that because of CV2 & and imshow()

*note: I'm using PIL 8.4.0 (Cant get the newest version, idk why)

**Comment by radarhere** [comment]
This was continued as https://github.com/python-pillow/Pillow/issues/6126
