### ISSUE TITLE
curl: (28) Failed to connect to sourceware.org port 443: Operation timed out

### ISSUE THREAD

**Issue by hugovk** [python-pillow/pillow-wheels#276]
There's been some timeouts, such as this on [linux / 3.10 musllinux x86_64](https://github.com/python-pillow/pillow-wheels/runs/5784311857?check_suite_focus=true#logs):

```
    0     0    0     0    0     0      0      0 --:--:--  0:02:04 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:05 --:--:--     0Still building...
  
    0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:08 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0
  curl: (28) Failed to connect to sourceware.org port 443 after 130355 ms: Operation timed out
  Error: Process completed with exit code 28.
```

([Full logs](https://github.com/python-pillow/pillow-wheels/files/8395954/8.txt))

Here's another:

* [linux-latest / 3.8 manylinux i686](https://github.com/python-pillow/pillow-wheels/runs/5782619375?check_suite_focus=true#logs)

Can we make this more robust?

https://sourceware.org/mirrors.html says:

> These sites mirror the free software ftp directory directly. The master sourceware.org server itself is usually overloaded.

**Comment by radarhere** [comment]
sourceware.org is being used to [try and download bzip2.](https://github.com/multi-build/multibuild/blob/bce1637e202cb52b0e7ea42baa1cccc894b82806/library_builders.sh#L185)

I've [uploaded that file to pillow-depends](https://github.com/python-pillow/pillow-depends/commit/b093b7d65d32679e506557159cf154845d184df6), so pillow-wheels should no longer try and download it from sourceware.org.

**Comment by hugovk** [comment]
Thanks, I've also made a PR to multibuild to use a mirror, that should be more reliable, help others, and not need us to keep our own pillow-depends mirror updated.

https://github.com/multi-build/multibuild/pull/467

**Comment by radarhere** [comment]
Have we done everything there is to do here?

**Comment by hugovk** [comment]
Yes, thanks!
