### ISSUE TITLE
Enable re-running failed jobs

### ISSUE THREAD

**Issue by hugovk** [python-pillow/pillow-wheels#277]
The first attempt at a release build had a single timeout caused by https://github.com/python-pillow/pillow-wheels/issues/276.

Luckily GitHub has a new feature to re-run only the failed jobs:

![image](https://user-images.githubusercontent.com/1324225/161250830-04c19a2c-5e0f-4c97-a767-87299c16db37.png)

https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#re-running-failed-jobs-in-a-workflow

But for some reason, that's not available here and we needed to re-run all jobs:

![image](https://user-images.githubusercontent.com/1324225/161250974-a3c644f4-1833-43f9-a13c-cb1b6810049b.png)

The second attempt had another job failing with a similar timeout. Again it required re-running all jobs (takes about 45 minutes).

Perhaps the "Re-run failed jobs" is unavailable due to this "cross-over" of dependant jobs?

![image](https://user-images.githubusercontent.com/1324225/161251179-10ee46af-6465-4677-998a-d27c15344f99.png)

---

Idea for testing: make all jobs a no-op so they don't actually take a long time to build, and make a single job always fail.

Could ask here or there:

> Still need help?
> [Ask the GitHub community](https://github.community/)
> [Contact support](https://support.github.com/contact)

**Comment by radarhere** [comment]
From 10 days ago, https://github.com/actions/runner/issues/432#issuecomment-1074561084
> We have temporarily disabled the feature for any run that references a reusable workflow while we iron out the issues. We hope to have those resolved towards the end of this week or early next week.

**Comment by radarhere** [comment]
This is working now.

I saw it on https://github.com/python-pillow/pillow-wheels/actions/runs/2102911684 and reran a failed job. They're all passing now, so you can no longer "Re-run failed jobs", meaning that the evidence is kind of gone... but the second run has a total duration of 16m 5s, which could only have happened with this feature.

**Comment by hugovk** [comment]
Good news, thanks!
