### ISSUE TITLE
Stripping the Pillow libraries fails makes pyinstaller binary fail at runtime

### ISSUE THREAD

**Issue by simaoafonso-pwt** [python-pillow/pillow-wheels#299]
### What did you do?

When using PyInstaller to freeze an application that contains pillow as a dependency, the `--strip` option runs `strip` on the libraries. This fails on the `_imaging` pillow library.

### What did you expect to happen?

The pillow C libraries should still be loaded when stripped.

I'm not *exactly* sure this is a Pillow issue, but since it works without stripping, I guess it is.

The unstripped binary is 3MB, stripping brings it down to 636kB.

[libs.tar.gz](https://github.com/python-pillow/Pillow/files/8681010/libs.tar.gz)

### What actually happened?

```
ELF load command address/offset not page-aligned
```

### What are your OS, Python and Pillow versions?

* OS: Arch Linux
* Python: 3.10.4
* Pillow: 9.1.0

```
$ cd "$(mktemp -d)"
$ python3.10 -m venv .
$ source bin/activate
$ pip install pillow pyinstaller
$ $EDITOR pilstrip.py
$ pyinstall -n pil-nostrip pilstrip.py
$ dist/pil-nostrip/pil-nostrip
<module 'PIL.Image' from '/tmp/tmp.5d4W8x0r8d/dist/pil-nostrip/PIL/Image.pyc'>
$ pyinstaller -n pil-strip --strip pilstrip.py
$ dist/pil-strip/pil-strip
Traceback (most recent call last):
  File "pilstrip.py", line 1, in <module>
    from PIL import Image
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "PIL/Image.py", line 132, in <module>
ImportError: /tmp/tmp.5d4W8x0r8d/dist/pil-strip/PIL/_imaging.cpython-310-x86_64-linux-gnu.so: ELF load command address/offset not page-aligned
[221404] Failed to execute script 'pilstrip' due to unhandled exception!
```

```python
from PIL import Image

print(Image)
```

**Comment by radarhere** [comment]
@simaoafonso-pwt Pillow 9.2.0 has now been released with this change

**Comment by simaoafonso-pwt** [comment]
Thanks for the heads up.
