### ISSUE TITLE
Alpine Linux MUSL Arm64

### ISSUE THREAD

**Issue by Slyrc** [python-pillow/pillow-wheels#346]
### What is your OS versions?

* Alpine Linux ARM64

Hi, 

I was searching on PyPI for Pillow MuslLinux_ARM64 wheel. ([https://pypi.org/project/Pillow/#files](https://pypi.org/project/Pillow/#files))

When searching for a MuslLinux Wheel I only find it for x86/x64. What does it need to provide an Arm64 Musl wheel?

Would be great to have this also for Arm64.

Thank you!

**Comment by radarhere** [comment]
Those are actually the x86_64 wheels. Here is a copy of the aarch64 wheels.

[Pillow-9.3.0-musllinux_1_1_aarch64.zip](https://github.com/python-pillow/pillow-wheels/files/10116577/Pillow-9.3.0-musllinux_1_1_aarch64.zip)

**Comment by hugovk** [comment]
No one tested but merged anyway 🚀

These will be in the 2023-01-02 release.

**Comment by radarhere** [comment]
Pillow 9.4.0 has now been released with these new wheels
