### ISSUE TITLE
Pillow wheels  >= 3.2.0 not installable on Mac OS X due to --with-pymalloc

### ISSUE THREAD

**Issue by znerol** [python-pillow/pillow-wheels#44]
Recent Pillow wheels are not installable on Mac OS X / Python 2.7. The last one which works is 3.1.1. Taking a close look at `pip --verbose install Pillow` reveals that older builds apparently are not compiled with any ABI flags (see [PEP 3149](https://www.python.org/dev/peps/pep-3149/)) (e.g. on https://pypi.python.org/pypi/Pillow/3.1.1 there is `Pillow-3.1.1-cp27-none-macosx_10...`) while newer ones apparently were compiled with `--with-pymalloc` (e.g. on https://pypi.python.org/pypi/Pillow/3.2.0 there is `Pillow-3.2.0-cp27-cp27m-macosx_10...`, note `-cp27m-` instead of `-none-` ).

Wheels built with a Python version built with `--with-pymalloc` are apparently incompatible with Mac OS X   Python interpreter (El Capitan in my case).

**Comment by znerol** [comment]
This might be due to the Python version being installed via `homebrew` and `pyenv`. Looks like the system Python is capable of using the prebuilt wheels.

**Comment by matthew-brett** [comment]
The wheels are meant to work with system Python, homebrew and Python.org Python - we test on those platforms - on OSX 10.9.

Right now the wheel install isn't working because there is a source release but no wheels for 3.4.0.

On my El Capitan system, I do get the wheel, when installing from a Python.org or system Python virtualenv - what Python are you using, that fails?  What pip version do you have?

**Comment by matthew-brett** [comment]
Sorry - to clarify - I do get the wheel for:

```
pip install --no-cache-dir pillow==3.3.1
```

**Comment by aclark4life** [comment]
@matthew-brett @znerol already closed this so I'm closing again.

**Comment by matthew-brett** [comment]
I reopened it because, if we can replicate what @znerol found, that is a bug in the wheel generation process.

**Comment by aclark4life** [comment]
Ah! Fair enough. Oh, I see the goal is not just system Python but homebrew too (what is pyenv?)

**Comment by matthew-brett** [comment]
pyenv is some machinery that compiles a new version of Python from source, and switches to the new compiled version.   We don't support pyenv because it has a highly unusual build configuration for OSX - see : https://github.com/yyuu/pyenv/issues/257#issuecomment-250987782

I wonder whether that is the problem that @znerol is seeing - @znerol - are you using pyenv?

**Comment by znerol** [comment]
@matthew-brett initially yes, I dropped it again after I ran into additional issues (unrelated to pillow).

**Comment by matthew-brett** [comment]
Can you replicate your problem outside pyenv?   If so, what Python / pip are you using?

**Comment by znerol** [comment]
No, with system python the Pillow wheel runs fine.

**Comment by matthew-brett** [comment]
If you read the pyenv thread, the pyenv build is incompatible with nearly all wheels.

**Comment by hugovk** [comment]
I got the wheel with OS X El Capitan (10.11.6 (15G1004)) and Homebrew Python:

```bash
⏚ [hugo:~] $ which python
/usr/local/bin/python
⏚ [hugo:~] $ python --version
Python 2.7.11
⏚ [hugo:~] $ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
⏚ [hugo:~] 26s $

```

```bash
⏚ [hugo:~] $ pip install -U pillow
Collecting pillow
  Downloading Pillow-3.4.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.4MB)
    100% |████████████████████████████████| 3.4MB 181kB/s 
Installing collected packages: pillow
  Found existing installation: Pillow 3.3.1
    Uninstalling Pillow-3.3.1:
      Successfully uninstalled Pillow-3.3.1
Successfully installed pillow-3.4.0
⏚ [hugo:~] 35s $ 
```

**Comment by matthew-brett** [comment]
OK - then I think this is a pyenv issue that should soon be fixed (see that thread).   Closing, but please re-open if you or anyone else can replicate the issue with Python other than pyenv.
