### ISSUE TITLE
x64 wheels are broken

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/pillow-wheels#58]
The build process for the x64 wheels is broken due to repos being inaccessible. I don't know if this is a temporary issue or not.

see https://travis-ci.org/python-pillow/pillow-wheels/jobs/218267819 for trace

**Comment by matthew-brett** [comment]
Ugh - this is because the CentOS 5 repositories that the manylinux docker image needs have been taken offline.  CentOS 5 just went end of life.  We need to update the docker image ASAP.

**Comment by matthew-brett** [comment]
See: https://github.com/pypa/manylinux/issues/100

**Comment by wiredfool** [comment]
Oof, that is unfortunate.

**Comment by wiredfool** [comment]
Working now, wheels are built. Thanks for your help @matthew-brett .
