### ISSUE TITLE
Linux builds fail: no rsync

### ISSUE THREAD

**Issue by hugovk** [python-pillow/pillow-wheels#76]
Since turning on cron builds a couple of days ago, the Linux jobs are failing. They were passing when the last changes were pushed on 1st January. (MacOS passed before and pass now.) 

Dependencies are failing to build because a missing rsync fails to fetch the zip files. 

```
/io/multibuild/common_utils.sh: line 107: rsync: command not found
/io/multibuild/library_builders.sh: line 99: cd: jpeg-9b: No such file or directory
```
https://travis-ci.org/python-pillow/pillow-wheels/jobs/347228468#L527

**Comment by matthew-brett** [comment]
Try updating the the latest multibuild - we worked around this.  It's a change in the manylinux docker image.

**Comment by radarhere** [comment]
For anyone looking at this issue, there is a conversation about this problem at https://github.com/python-pillow/pillow-wheels/pull/78#issuecomment-372239976
